import {
  AudioMergeIcon,
  DenoiseIcon,
  FadeIcon,
  MicIcon,
  MusicTagIcon,
  NormalizeIcon,
  ReverseIcon,
  SilenceIcon,
  SpeedIcon,
  TrimIcon,
  VolumeIcon,
  WaveformIcon,
} from "@/components/icons/audio";
import { ConvertIcon } from "@/components/icons/image";

export const audioTools = [
  {
    title: "Convert",
    description: "Convert between audio formats",
    href: "/audio/convert",
    icon: ConvertIcon,
    category: "convert",
    colorClass: "tool-audio-convert",
  },
  {
    title: "Trim Audio",
    description: "Cut audio to specific start and end time",
    href: "/audio/trim",
    icon: TrimIcon,
    category: "edit",
    colorClass: "tool-audio-trim",
  },
  {
    title: "Volume",
    description: "Increase or decrease audio volume",
    href: "/audio/volume",
    icon: VolumeIcon,
    category: "edit",
    colorClass: "tool-audio-volume",
  },
  {
    title: "Speed",
    description: "Speed up or slow down audio playback",
    href: "/audio/speed",
    icon: SpeedIcon,
    category: "edit",
    colorClass: "tool-audio-speed",
  },
  {
    title: "Record",
    description: "Record audio from your microphone",
    href: "/audio/record",
    icon: MicIcon,
    category: "create",
    colorClass: "tool-audio-record",
  },
  {
    title: "Waveform",
    description: "Generate waveform image from audio",
    href: "/audio/waveform",
    icon: WaveformIcon,
    category: "convert",
    colorClass: "tool-audio-waveform",
  },
  {
    title: "Fade",
    description: "Add fade in and fade out effects",
    href: "/audio/fade",
    icon: FadeIcon,
    category: "effects",
    colorClass: "tool-audio-fade",
  },
  {
    title: "Denoise",
    description: "Remove background noise from recordings",
    href: "/audio/denoise",
    icon: DenoiseIcon,
    category: "effects",
    colorClass: "tool-audio-denoise",
  },
  {
    title: "Normalize",
    description: "Make audio volume consistent",
    href: "/audio/normalize",
    icon: NormalizeIcon,
    category: "edit",
    colorClass: "tool-audio-normalize",
  },
  {
    title: "Remove Silence",
    description: "Trim silent parts from audio",
    href: "/audio/remove-silence",
    icon: SilenceIcon,
    category: "edit",
    colorClass: "tool-audio-silence",
  },
  {
    title: "Merge",
    description: "Combine multiple audio files",
    href: "/audio/merge",
    icon: AudioMergeIcon,
    category: "edit",
    colorClass: "tool-audio-merge",
  },
  {
    title: "Reverse",
    description: "Play audio backwards",
    href: "/audio/reverse",
    icon: ReverseIcon,
    category: "effects",
    colorClass: "tool-audio-reverse",
  },
  {
    title: "Audio Metadata",
    description: "View, edit, or strip ID3 tags for MP3 files",
    href: "/audio/metadata",
    icon: MusicTagIcon,
    category: "edit",
    colorClass: "tool-audio-metadata",
  },
];

export const audioCategoryLabels: Record<string, string> = {
  edit: "Edit",
  create: "Create",
  effects: "Effects",
  convert: "Convert",
};
