import {
  AudioMergeIcon,
  DenoiseIcon,
  FadeIcon,
  MicIcon,
  MusicTagIcon,
  NormalizeIcon,
  ReverseIcon,
  SilenceIcon,
  SpeedIcon,
  TrimIcon,
  VolumeIcon,
  WaveformIcon,
} from "@/components/icons/audio";
import { ConvertIcon } from "@/components/icons/image";
import { CompressIcon } from "@/components/icons/pdf";

export const audioTools = [
  {
    title: "Compress",
    description: "Reduce audio file size",
    href: "/audio/compress",
    icon: CompressIcon,
    category: "optimize",
    colorClass: "tool-audio-compress",
    keywords: ["shrink", "smaller", "reduce size", "aac", "bitrate"],
  },
  {
    title: "Convert",
    description: "Convert between audio formats",
    href: "/audio/convert",
    icon: ConvertIcon,
    category: "convert",
    colorClass: "tool-audio-convert",
    keywords: [
      "mp3 to wav", "wav to mp3", "mp3 to ogg", "ogg to mp3",
      "mp3 to aac", "flac to mp3", "m4a to mp3", "wav to ogg",
      "audio format", "change format",
    ],
  },
  {
    title: "Trim Audio",
    description: "Cut audio to specific start and end time",
    href: "/audio/trim",
    icon: TrimIcon,
    category: "edit",
    colorClass: "tool-audio-trim",
    keywords: ["cut", "clip", "shorten", "start end"],
  },
  {
    title: "Volume",
    description: "Increase or decrease audio volume",
    href: "/audio/volume",
    icon: VolumeIcon,
    category: "edit",
    colorClass: "tool-audio-volume",
    keywords: ["louder", "quieter", "gain", "amplify", "boost"],
  },
  {
    title: "Speed",
    description: "Speed up or slow down audio playback",
    href: "/audio/speed",
    icon: SpeedIcon,
    category: "edit",
    colorClass: "tool-audio-speed",
    keywords: ["faster", "slower", "tempo", "playback rate", "2x", "0.5x"],
  },
  {
    title: "Record",
    description: "Record audio from your microphone",
    href: "/audio/record",
    icon: MicIcon,
    category: "create",
    colorClass: "tool-audio-record",
    keywords: ["microphone", "mic", "voice", "capture"],
  },
  {
    title: "Waveform",
    description: "Generate waveform image from audio",
    href: "/audio/waveform",
    icon: WaveformIcon,
    category: "convert",
    colorClass: "tool-audio-waveform",
    keywords: ["visualization", "visualize", "wave", "audio image", "soundwave"],
  },
  {
    title: "Fade",
    description: "Add fade in and fade out effects",
    href: "/audio/fade",
    icon: FadeIcon,
    category: "effects",
    colorClass: "tool-audio-fade",
    keywords: ["fade in", "fade out", "intro", "outro", "crossfade"],
  },
  {
    title: "Denoise",
    description: "Remove background noise from recordings",
    href: "/audio/denoise",
    icon: DenoiseIcon,
    category: "effects",
    colorClass: "tool-audio-denoise",
    keywords: ["noise removal", "clean audio", "hiss", "hum", "background noise"],
  },
  {
    title: "Normalize",
    description: "Make audio volume consistent",
    href: "/audio/normalize",
    icon: NormalizeIcon,
    category: "edit",
    colorClass: "tool-audio-normalize",
    keywords: ["level", "consistent volume", "even out", "loudness"],
  },
  {
    title: "Remove Silence",
    description: "Trim silent parts from audio",
    href: "/audio/remove-silence",
    icon: SilenceIcon,
    category: "edit",
    colorClass: "tool-audio-silence",
    keywords: ["trim silence", "dead air", "gaps", "quiet parts"],
  },
  {
    title: "Merge",
    description: "Combine multiple audio files",
    href: "/audio/merge",
    icon: AudioMergeIcon,
    category: "edit",
    colorClass: "tool-audio-merge",
    keywords: ["join", "concatenate", "combine", "append"],
  },
  {
    title: "Reverse",
    description: "Play audio backwards",
    href: "/audio/reverse",
    icon: ReverseIcon,
    category: "effects",
    colorClass: "tool-audio-reverse",
    keywords: ["backwards", "reverse playback"],
  },
  {
    title: "Audio Metadata",
    description: "View, edit, or strip ID3 tags for MP3 files",
    href: "/audio/metadata",
    icon: MusicTagIcon,
    category: "edit",
    colorClass: "tool-audio-metadata",
    keywords: ["id3", "tags", "artist", "album", "title", "cover art"],
  },
];

export const audioCategoryLabels: Record<string, string> = {
  optimize: "Optimize",
  edit: "Edit",
  create: "Create",
  effects: "Effects",
  convert: "Convert",
};
