import {
  Base64Icon,
  BlurIcon,
  BorderIcon,
  BrightnessIcon,
  CollageIcon,
  ConvertIcon,
  CropIcon,
  FaviconIcon,
  FiltersIcon,
  HeicIcon,
  ImageCompressIcon,
  PaletteIcon,
  RemoveBgIcon,
  ResizeIcon,
  ScreenshotIcon,
} from "@/components/icons/image";
import { MetadataIcon, RotateIcon, WatermarkIcon } from "@/components/icons/pdf";
import { EditIcon } from "@/components/icons/ui";

export const imageTools = [
  {
    title: "Compress",
    description: "Reduce image file size while keeping quality",
    href: "/image/compress",
    icon: ImageCompressIcon,
    category: "optimize",
    colorClass: "tool-image-compress",
  },
  {
    title: "Convert",
    description: "PNG, JPEG, WebP · SVG to raster",
    href: "/image/convert",
    icon: ConvertIcon,
    category: "convert",
    colorClass: "tool-convert",
  },
  {
    title: "Edit Image",
    description: "Add text, shapes, drawings, stamps, and signatures",
    href: "/image/edit",
    icon: EditIcon,
    category: "edit",
    colorClass: "tool-image-edit",
  },
  {
    title: "Resize",
    description: "Change image dimensions with presets or custom sizes",
    href: "/image/resize",
    icon: ResizeIcon,
    category: "edit",
    colorClass: "tool-resize",
  },
  {
    title: "Crop",
    description: "Crop images with custom aspect ratios",
    href: "/image/crop",
    icon: CropIcon,
    category: "edit",
    colorClass: "tool-crop",
  },
  {
    title: "Remove Background",
    description: "Remove image backgrounds with AI",
    href: "/image/remove-bg",
    icon: RemoveBgIcon,
    category: "ai",
    colorClass: "tool-remove-bg",
  },
  {
    title: "Screenshot Beautifier",
    description: "Add gradient backgrounds and frames to screenshots",
    href: "/image/screenshot",
    icon: ScreenshotIcon,
    category: "edit",
    colorClass: "tool-screenshot",
  },
  {
    title: "Collage Maker",
    description: "Combine multiple images into one",
    href: "/image/collage",
    icon: CollageIcon,
    category: "edit",
    colorClass: "tool-collage",
  },
  {
    title: "Blur & Pixelate",
    description: "Hide sensitive areas in images",
    href: "/image/blur",
    icon: BlurIcon,
    category: "privacy",
    colorClass: "tool-blur",
  },
  {
    title: "Image Metadata",
    description: "View EXIF data, GPS location, then strip for privacy",
    href: "/image/strip-metadata",
    icon: MetadataIcon,
    category: "privacy",
    colorClass: "tool-strip-metadata",
  },
  {
    title: "Rotate & Flip",
    description: "Rotate 90\u00b0, 180\u00b0, 270\u00b0 or flip images",
    href: "/image/rotate",
    icon: RotateIcon,
    category: "edit",
    colorClass: "tool-rotate-image",
  },
  {
    title: "Adjust",
    description: "Fine-tune brightness, contrast, and saturation",
    href: "/image/adjust",
    icon: BrightnessIcon,
    category: "edit",
    colorClass: "tool-adjust",
  },
  {
    title: "Filters",
    description: "Apply grayscale, sepia, or invert effects",
    href: "/image/filters",
    icon: FiltersIcon,
    category: "edit",
    colorClass: "tool-filters",
  },
  {
    title: "Watermark",
    description: "Add text watermarks to your images",
    href: "/image/watermark",
    icon: WatermarkIcon,
    category: "edit",
    colorClass: "tool-image-watermark",
  },
  {
    title: "Add Border",
    description: "Add a colored border around images",
    href: "/image/border",
    icon: BorderIcon,
    category: "edit",
    colorClass: "tool-border",
  },
  {
    title: "HEIC \u2192 JPEG",
    description: "Convert iPhone photos to standard JPEG",
    href: "/image/heic-to-jpeg",
    icon: HeicIcon,
    category: "convert",
    colorClass: "tool-heic",
  },
  {
    title: "To Base64",
    description: "Convert image to Base64 string for embedding",
    href: "/image/to-base64",
    icon: Base64Icon,
    category: "convert",
    colorClass: "tool-base64",
  },
  {
    title: "Favicon Generator",
    description: "Generate all favicon sizes from one image",
    href: "/image/favicon",
    icon: FaviconIcon,
    category: "convert",
    colorClass: "tool-favicon",
  },
  {
    title: "Color Palette",
    description: "Extract dominant colors from images",
    href: "/image/palette",
    icon: PaletteIcon,
    category: "convert",
    colorClass: "tool-palette",
  },
];

export const imageCategoryLabels: Record<string, string> = {
  optimize: "Optimize",
  edit: "Edit",
  convert: "Convert",
  privacy: "Privacy",
  ai: "AI",
};
