import {
  Base64Icon,
  BlurIcon,
  BorderIcon,
  BrightnessIcon,
  CollageIcon,
  ConvertIcon,
  CropIcon,
  FaviconIcon,
  FiltersIcon,
  HeicIcon,
  ImageCompressIcon,
  PaletteIcon,
  RemoveBgIcon,
  ResizeIcon,
  ScreenshotIcon,
} from "@/components/icons/image";
import { MetadataIcon, RotateIcon, WatermarkIcon } from "@/components/icons/pdf";
import { EditIcon } from "@/components/icons/ui";

export const imageTools = [
  {
    title: "Compress",
    description: "Reduce image file size while keeping quality",
    href: "/image/compress",
    icon: ImageCompressIcon,
    category: "optimize",
    colorClass: "tool-image-compress",
    keywords: ["shrink", "smaller", "optimize", "reduce size", "file size"],
  },
  {
    title: "Convert",
    description: "PNG, JPEG, WebP · SVG to raster",
    href: "/image/convert",
    icon: ConvertIcon,
    category: "convert",
    colorClass: "tool-convert",
    keywords: [
      "png to jpg", "png to jpeg", "png to webp",
      "jpg to png", "jpg to webp", "jpeg to png", "jpeg to webp",
      "webp to png", "webp to jpg", "webp to jpeg",
      "svg to png", "svg to jpg", "svg to jpeg", "svg to webp",
      "image format", "change format",
    ],
  },
  {
    title: "Edit Image",
    description: "Add text, shapes, drawings, stamps, and signatures",
    href: "/image/edit",
    icon: EditIcon,
    category: "edit",
    colorClass: "tool-image-edit",
    keywords: ["annotate", "draw", "sign", "paint", "markup", "text on image"],
  },
  {
    title: "Resize",
    description: "Change image dimensions with presets or custom sizes",
    href: "/image/resize",
    icon: ResizeIcon,
    category: "edit",
    colorClass: "tool-resize",
    keywords: ["scale", "dimensions", "width", "height", "pixels", "make smaller", "make bigger", "enlarge"],
  },
  {
    title: "Crop",
    description: "Crop images with custom aspect ratios",
    href: "/image/crop",
    icon: CropIcon,
    category: "edit",
    colorClass: "tool-crop",
    keywords: ["trim", "cut", "aspect ratio", "square", "16:9", "4:3"],
  },
  {
    title: "Remove Background",
    description: "Remove image backgrounds with AI",
    href: "/image/remove-bg",
    icon: RemoveBgIcon,
    category: "ai",
    colorClass: "tool-remove-bg",
    keywords: ["transparent", "cutout", "background remover", "bg remove", "no background", "erase background"],
  },
  {
    title: "Screenshot Beautifier",
    description: "Add gradient backgrounds and frames to screenshots",
    href: "/image/screenshot",
    icon: ScreenshotIcon,
    category: "edit",
    colorClass: "tool-screenshot",
    keywords: ["mockup", "frame", "gradient", "beautify", "presentation"],
  },
  {
    title: "Collage Maker",
    description: "Combine multiple images into one",
    href: "/image/collage",
    icon: CollageIcon,
    category: "edit",
    colorClass: "tool-collage",
    keywords: ["grid", "combine", "merge", "layout", "photo grid", "stitch"],
  },
  {
    title: "Blur & Pixelate",
    description: "Hide sensitive areas in images",
    href: "/image/blur",
    icon: BlurIcon,
    category: "privacy",
    colorClass: "tool-blur",
    keywords: ["censor", "redact", "hide", "mosaic", "obscure", "face blur"],
  },
  {
    title: "Image Metadata",
    description: "View EXIF data, GPS location, then strip for privacy",
    href: "/image/strip-metadata",
    icon: MetadataIcon,
    category: "privacy",
    colorClass: "tool-strip-metadata",
    keywords: ["exif", "gps", "location", "strip", "remove metadata", "photo info", "camera info"],
  },
  {
    title: "Rotate & Flip",
    description: "Rotate 90\u00b0, 180\u00b0, 270\u00b0 or flip images",
    href: "/image/rotate",
    icon: RotateIcon,
    category: "edit",
    colorClass: "tool-rotate-image",
    keywords: ["mirror", "flip horizontal", "flip vertical", "turn", "orientation"],
  },
  {
    title: "Adjust",
    description: "Fine-tune brightness, contrast, and saturation",
    href: "/image/adjust",
    icon: BrightnessIcon,
    category: "edit",
    colorClass: "tool-adjust",
    keywords: ["brightness", "contrast", "saturation", "exposure", "lighten", "darken"],
  },
  {
    title: "Filters",
    description: "Apply grayscale, sepia, or invert effects",
    href: "/image/filters",
    icon: FiltersIcon,
    category: "edit",
    colorClass: "tool-filters",
    keywords: ["grayscale", "sepia", "invert", "black and white", "b&w", "effect", "vintage", "noir"],
  },
  {
    title: "Watermark",
    description: "Add text watermarks to your images",
    href: "/image/watermark",
    icon: WatermarkIcon,
    category: "edit",
    colorClass: "tool-image-watermark",
    keywords: ["copyright", "overlay", "protect", "branding", "stamp text"],
  },
  {
    title: "Add Border",
    description: "Add a colored border around images",
    href: "/image/border",
    icon: BorderIcon,
    category: "edit",
    colorClass: "tool-border",
    keywords: ["frame", "outline", "padding", "edge"],
  },
  {
    title: "HEIC \u2192 JPEG",
    description: "Convert iPhone photos to standard JPEG",
    href: "/image/heic-to-jpeg",
    icon: HeicIcon,
    category: "convert",
    colorClass: "tool-heic",
    keywords: ["heic to jpg", "heif to jpg", "iphone photo", "apple photo", "heic convert"],
  },
  {
    title: "To Base64",
    description: "Convert image to Base64 string for embedding",
    href: "/image/to-base64",
    icon: Base64Icon,
    category: "convert",
    colorClass: "tool-base64",
    keywords: ["data uri", "data url", "embed", "inline", "encode"],
  },
  {
    title: "Favicon Generator",
    description: "Generate all favicon sizes from one image",
    href: "/image/favicon",
    icon: FaviconIcon,
    category: "convert",
    colorClass: "tool-favicon",
    keywords: ["ico", "icon", "website icon", "apple touch icon", "android icon", "pwa icon"],
  },
  {
    title: "Color Palette",
    description: "Extract dominant colors from images",
    href: "/image/palette",
    icon: PaletteIcon,
    category: "convert",
    colorClass: "tool-palette",
    keywords: ["colors", "extract colors", "dominant color", "swatch", "color picker", "hex"],
  },
];

export const imageCategoryLabels: Record<string, string> = {
  optimize: "Optimize",
  edit: "Edit",
  convert: "Convert",
  privacy: "Privacy",
  ai: "AI",
};
