
import { ExtractImageIcon, GrayscaleIcon, ImageIcon } from "@/components/icons/image";
import {
  ArchiveIcon,
  BookIcon,
  CompressIcon,
  DeletePagesIcon,
  DuplicateIcon,
  FileIcon,
  HtmlIcon,
  MergeIcon,
  MetadataIcon,
  NumbersIcon,
  OcrIcon,
  OrganizeIcon,
  PptxIcon,
  WordIcon,
  ExcelIcon,
  ReversePagesIcon,
  RotateIcon,

  SignatureIcon,
  SplitIcon,
  TextIcon,
  WatermarkIcon,
} from "@/components/icons/pdf";
import { EditIcon, LockIcon, UnlockIcon } from "@/components/icons/ui";
import { ToolSearch } from "@/components/shared/ToolSearch";

export const pdfTools = [
  {
    title: "Compress",
    description: "Reduce file size while keeping quality",
    href: "/compress",
    icon: CompressIcon,
    category: "optimize",
    colorClass: "tool-compress",
    keywords: ["shrink", "smaller pdf", "reduce size", "optimize"],
  },
  {
    title: "Edit PDF",
    description: "Add text, signatures, shapes, and annotations",
    href: "/edit",
    icon: EditIcon,
    category: "edit",
    colorClass: "tool-edit",
    keywords: ["annotate", "markup", "draw", "highlight", "text", "sign"],
  },
  {
    title: "Merge PDF",
    description: "Combine multiple PDFs into one document",
    href: "/merge",
    icon: MergeIcon,
    category: "organize",
    colorClass: "tool-merge",
    keywords: ["combine", "join", "concatenate", "append"],
  },
  {
    title: "Split PDF",
    description: "Extract pages or divide into multiple files",
    href: "/split",
    icon: SplitIcon,
    category: "organize",
    colorClass: "tool-split",
    keywords: ["separate", "divide", "extract pages", "break apart"],
  },
  {
    title: "Images → PDF",
    description: "Create a PDF from your images",
    href: "/images-to-pdf",
    icon: FileIcon,
    category: "convert",
    colorClass: "tool-images-to-pdf",
    keywords: ["jpg to pdf", "png to pdf", "photo to pdf", "image to pdf", "pictures to pdf"],
  },
  {
    title: "PDF → Images",
    description: "Convert pages to JPG or PNG",
    href: "/pdf-to-images",
    icon: ImageIcon,
    category: "convert",
    colorClass: "tool-pdf-to-images",
    keywords: ["pdf to jpg", "pdf to png", "pdf to image", "screenshot pages", "export pages"],
  },
  {
    title: "Sign PDF",
    description: "Add your signature to documents",
    href: "/sign",
    icon: SignatureIcon,
    category: "edit",
    colorClass: "tool-sign",
    keywords: ["signature", "e-sign", "esign", "autograph"],
  },
  {
    title: "Encrypt PDF",
    description: "Add password protection to your PDF",
    href: "/encrypt",
    icon: LockIcon,
    category: "security",
    colorClass: "tool-encrypt",
    keywords: ["password", "protect", "lock", "secure"],
  },
  {
    title: "Decrypt PDF",
    description: "Remove password from protected PDFs",
    href: "/decrypt",
    icon: UnlockIcon,
    category: "security",
    colorClass: "tool-decrypt",
    keywords: ["unlock", "remove password", "unprotect"],
  },
  {
    title: "Organize PDF",
    description: "Sort, add and delete pages with drag & drop",
    href: "/organize",
    icon: OrganizeIcon,
    category: "organize",
    colorClass: "tool-organize",
    keywords: ["reorder", "rearrange", "sort pages", "move pages", "drag drop"],
  },
  {
    title: "Grayscale",
    description: "Convert color PDFs to black and white",
    href: "/grayscale",
    icon: GrayscaleIcon,
    category: "convert",
    colorClass: "tool-grayscale",
    keywords: ["black and white", "b&w", "monochrome", "desaturate"],
  },
  {
    title: "PDF to PDF/A",
    description: "Convert to archival format for preservation",
    href: "/pdf-to-pdfa",
    icon: ArchiveIcon,
    category: "convert",
    colorClass: "tool-pdfa",
    keywords: ["archive", "long term", "preservation", "iso", "compliance"],
  },
  {
    title: "Markdown → PDF",
    description: "Convert Markdown with LaTeX math to PDF",
    href: "/markdown-to-pdf",
    icon: TextIcon,
    category: "convert",
    colorClass: "tool-markdown-to-pdf",
    keywords: ["md to pdf", "markdown", "latex", "math equations"],
  },
  {
    title: "HTML → PDF",
    description: "Convert HTML with CSS to PDF documents",
    href: "/html-to-pdf",
    icon: HtmlIcon,
    category: "convert",
    colorClass: "tool-html-to-pdf",
    keywords: ["webpage to pdf", "website to pdf", "html"],
  },
  {
    title: "Rotate",
    description: "Rotate pages in any direction",
    href: "/rotate",
    icon: RotateIcon,
    category: "organize",
    colorClass: "tool-rotate",
    keywords: ["turn", "orientation", "landscape", "portrait"],
  },
  {
    title: "Watermark",
    description: "Add text watermarks to documents",
    href: "/watermark",
    icon: WatermarkIcon,
    category: "edit",
    colorClass: "tool-watermark",
    keywords: ["stamp", "overlay", "copyright", "branding", "confidential", "draft"],
  },
  {
    title: "Page Numbers",
    description: "Add page numbers to your PDF",
    href: "/page-numbers",
    icon: NumbersIcon,
    category: "edit",
    colorClass: "tool-page-numbers",
    keywords: ["numbering", "footer", "header", "pagination"],
  },
  {
    title: "OCR",
    description: "Extract text from scanned docs",
    href: "/ocr",
    icon: OcrIcon,
    category: "convert",
    colorClass: "tool-ocr",
    keywords: ["scan", "recognize text", "scanned pdf", "image to text", "searchable"],
  },
  {
    title: "Reverse Pages",
    description: "Flip the order of all pages",
    href: "/reverse",
    icon: ReversePagesIcon,
    category: "organize",
    colorClass: "tool-reverse",
    keywords: ["flip order", "backwards", "invert order"],
  },
  {
    title: "PDF → Text",
    description: "Extract text content from PDFs",
    href: "/pdf-to-text",
    icon: TextIcon,
    category: "convert",
    colorClass: "tool-convert",
    keywords: ["extract text", "copy text", "pdf to txt", "plain text"],
  },
  {
    title: "Duplicate Pages",
    description: "Copy and append pages to your PDF",
    href: "/duplicate",
    icon: DuplicateIcon,
    category: "organize",
    colorClass: "tool-duplicate",
    keywords: ["copy pages", "clone", "repeat"],
  },
  {
    title: "Delete Pages",
    description: "Remove unwanted pages from PDF",
    href: "/delete",
    icon: DeletePagesIcon,
    category: "organize",
    colorClass: "tool-delete",
    keywords: ["remove pages", "drop pages", "trim pdf"],
  },
  {
    title: "PDF Metadata",
    description: "View, edit, or strip document properties",
    href: "/metadata",
    icon: MetadataIcon,
    category: "edit",
    colorClass: "tool-metadata",
    keywords: ["properties", "author", "title", "subject", "strip metadata"],
  },
  {
    title: "Extract Images",
    description: "Pull all images from a PDF",
    href: "/extract-images",
    icon: ExtractImageIcon,
    category: "convert",
    colorClass: "tool-extract-images",
    keywords: ["get images", "save images", "pull photos"],
  },
  {
    title: "PDF → EPUB",
    description: "Convert PDFs to ebook format",
    href: "/pdf-to-epub",
    icon: BookIcon,
    category: "convert",
    colorClass: "tool-convert",
    keywords: ["ebook", "kindle", "reader", "epub"],
  },
  {
    title: "PPTX → PDF",
    description: "Convert PowerPoint presentations to PDF",
    href: "/pptx-to-pdf",
    icon: PptxIcon,
    category: "convert",
    colorClass: "tool-pptx-to-pdf",
    keywords: ["powerpoint", "ppt", "slides", "presentation to pdf"],
  },
  {
    title: "DOCX → PDF",
    description: "Convert Word documents to PDF",
    href: "/docx-to-pdf",
    icon: WordIcon,
    category: "convert",
    colorClass: "tool-docx-to-pdf",
    keywords: ["word to pdf", "docx", "doc", "document to pdf", "odt"],
  },
  {
    title: "XLSX → PDF",
    description: "Convert Excel spreadsheets to PDF",
    href: "/xlsx-to-pdf",
    icon: ExcelIcon,
    category: "convert",
    colorClass: "tool-xlsx-to-pdf",
    keywords: ["excel to pdf", "xlsx", "xls", "spreadsheet to pdf", "ods"],
  },
];

export const pdfCategoryLabels: Record<string, string> = {
  organize: "Organize",
  optimize: "Optimize",
  convert: "Convert",
  edit: "Edit",
  security: "Security",
};

export function PdfToolsGrid() {
  return <ToolSearch tools={pdfTools} categoryLabels={pdfCategoryLabels} placeholder="Search PDF tools..." />;
}
