"use client";

import { EditIcon, LockIcon, UnlockIcon } from "@/components/icons/ui";
import {
  ArchiveIcon,
  BookIcon,
  CompressIcon,
  DeletePagesIcon,
  DuplicateIcon,
  FileIcon,
  HtmlIcon,
  MergeIcon,
  MetadataIcon,
  NumbersIcon,
  OcrIcon,
  OrganizeIcon,
  ReversePagesIcon,
  RotateIcon,
  SanitizeIcon,
  SignatureIcon,
  SplitIcon,
  TextIcon,
  WatermarkIcon,
} from "@/components/icons/pdf";
import { GrayscaleIcon, ExtractImageIcon, ImageIcon } from "@/components/icons/image";
import { ToolSearch } from "@/components/shared/ToolSearch";

const tools = [
  {
    title: "Edit PDF",
    description: "Add text, signatures, shapes, and annotations",
    href: "/edit",
    icon: EditIcon,
    category: "edit",
    colorClass: "tool-edit",
  },
  {
    title: "Organize PDF",
    description: "Sort, add and delete pages with drag & drop",
    href: "/organize",
    icon: OrganizeIcon,
    category: "organize",
    colorClass: "tool-organize",
  },
  {
    title: "Merge PDF",
    description: "Combine multiple PDFs into one document",
    href: "/merge",
    icon: MergeIcon,
    category: "organize",
    colorClass: "tool-merge",
  },
  {
    title: "Split PDF",
    description: "Extract pages or divide into multiple files",
    href: "/split",
    icon: SplitIcon,
    category: "organize",
    colorClass: "tool-split",
  },
  {
    title: "Compress",
    description: "Reduce file size while keeping quality",
    href: "/compress",
    icon: CompressIcon,
    category: "optimize",
    colorClass: "tool-compress",
  },
  {
    title: "Grayscale",
    description: "Convert color PDFs to black and white",
    href: "/grayscale",
    icon: GrayscaleIcon,
    category: "convert",
    colorClass: "tool-grayscale",
  },
  {
    title: "PDF to PDF/A",
    description: "Convert to archival format for preservation",
    href: "/pdf-to-pdfa",
    icon: ArchiveIcon,
    category: "convert",
    colorClass: "tool-pdfa",
  },
  {
    title: "PDF → Images",
    description: "Convert pages to JPG or PNG",
    href: "/pdf-to-images",
    icon: ImageIcon,
    category: "convert",
    colorClass: "tool-pdf-to-images",
  },
  {
    title: "Images → PDF",
    description: "Create a PDF from your images",
    href: "/images-to-pdf",
    icon: FileIcon,
    category: "convert",
    colorClass: "tool-images-to-pdf",
  },
  {
    title: "Markdown → PDF",
    description: "Convert Markdown with LaTeX math to PDF",
    href: "/markdown-to-pdf",
    icon: TextIcon,
    category: "convert",
    colorClass: "tool-markdown-to-pdf",
  },
  {
    title: "HTML → PDF",
    description: "Convert HTML with CSS to PDF documents",
    href: "/html-to-pdf",
    icon: HtmlIcon,
    category: "convert",
    colorClass: "tool-html-to-pdf",
  },
  {
    title: "Rotate",
    description: "Rotate pages in any direction",
    href: "/rotate",
    icon: RotateIcon,
    category: "organize",
    colorClass: "tool-rotate",
  },
  {
    title: "Watermark",
    description: "Add text watermarks to documents",
    href: "/watermark",
    icon: WatermarkIcon,
    category: "edit",
    colorClass: "tool-watermark",
  },
  {
    title: "Page Numbers",
    description: "Add page numbers to your PDF",
    href: "/page-numbers",
    icon: NumbersIcon,
    category: "edit",
    colorClass: "tool-page-numbers",
  },
  {
    title: "OCR",
    description: "Extract text from scanned docs",
    href: "/ocr",
    icon: OcrIcon,
    category: "convert",
    colorClass: "tool-ocr",
  },
  {
    title: "Sign PDF",
    description: "Add your signature to documents",
    href: "/sign",
    icon: SignatureIcon,
    category: "edit",
    colorClass: "tool-sign",
  },
  {
    title: "Sanitize PDF",
    description: "Remove metadata and hidden data",
    href: "/sanitize",
    icon: SanitizeIcon,
    category: "security",
    colorClass: "tool-sanitize",
  },
  {
    title: "Encrypt PDF",
    description: "Add password protection to your PDF",
    href: "/encrypt",
    icon: LockIcon,
    category: "security",
    colorClass: "tool-encrypt",
  },
  {
    title: "Decrypt PDF",
    description: "Remove password from protected PDFs",
    href: "/decrypt",
    icon: UnlockIcon,
    category: "security",
    colorClass: "tool-decrypt",
  },
  {
    title: "Reverse Pages",
    description: "Flip the order of all pages",
    href: "/reverse",
    icon: ReversePagesIcon,
    category: "organize",
    colorClass: "tool-reverse",
  },
  {
    title: "PDF → Text",
    description: "Extract text content from PDFs",
    href: "/pdf-to-text",
    icon: TextIcon,
    category: "convert",
    colorClass: "tool-convert",
  },
  {
    title: "Duplicate Pages",
    description: "Copy and append pages to your PDF",
    href: "/duplicate",
    icon: DuplicateIcon,
    category: "organize",
    colorClass: "tool-duplicate",
  },
  {
    title: "Delete Pages",
    description: "Remove unwanted pages from PDF",
    href: "/delete",
    icon: DeletePagesIcon,
    category: "organize",
    colorClass: "tool-delete",
  },
  {
    title: "PDF Metadata",
    description: "View and edit document properties",
    href: "/metadata",
    icon: MetadataIcon,
    category: "edit",
    colorClass: "tool-metadata",
  },
  {
    title: "Extract Images",
    description: "Pull all images from a PDF",
    href: "/extract-images",
    icon: ExtractImageIcon,
    category: "convert",
    colorClass: "tool-extract-images",
  },
  {
    title: "PDF → EPUB",
    description: "Convert PDFs to ebook format",
    href: "/pdf-to-epub",
    icon: BookIcon,
    category: "convert",
    colorClass: "tool-convert",
  },
];

const categoryLabels: Record<string, string> = {
  organize: "Organize",
  optimize: "Optimize",
  convert: "Convert",
  edit: "Edit",
  security: "Security",
};

export function PdfToolsGrid() {
  return <ToolSearch tools={tools} categoryLabels={categoryLabels} placeholder="Search PDF tools..." />;
}
