import { CaptionIcon, ExtractIcon } from "@/components/icons/audio";
import {
  AddAudioIcon,
  RemoveAudioIcon,
  VideoCompressIcon,
  VideoConvertIcon,
  VideoFlipIcon,
  VideoMergeIcon,
  VideoMetadataIcon,
  VideoRotateIcon,
  VideoSpeedIcon,
  VideoToGifIcon,
  VideoTrimIcon,
} from "@/components/icons/video";

export const videoTools = [
  {
    title: "Compress",
    description: "Reduce video or GIF file size with quality control",
    href: "/video/compress",
    icon: VideoCompressIcon,
    category: "optimize",
    colorClass: "tool-video-compress",
    keywords: ["shrink", "smaller", "reduce size", "bitrate", "compress gif", "shrink gif", "gif compressor"],
  },
  {
    title: "Trim",
    description: "Visually select and cut video clips",
    href: "/video/trim",
    icon: VideoTrimIcon,
    category: "edit",
    colorClass: "tool-video-trim",
    keywords: ["cut", "clip", "shorten", "start end", "cut video", "video cutter"],
  },
  {
    title: "Convert",
    description: "Convert between video formats",
    href: "/video/convert",
    icon: VideoConvertIcon,
    category: "convert",
    colorClass: "tool-video-convert",
    keywords: ["mp4 to webm", "webm to mp4", "mov to mp4", "avi to mp4", "mkv to mp4", "video format", "change format"],
    io: {
      from: ["mp4", "mov", "mkv", "avi", "webm", "flv", "wmv", "m4v", "video"],
      to: ["mp4", "webm", "mov", "mkv", "avi", "gif"],
    },
  },
  {
    title: "Remove Audio",
    description: "Strip audio track from video",
    href: "/video/remove-audio",
    icon: RemoveAudioIcon,
    category: "edit",
    colorClass: "tool-video-remove-audio",
    keywords: ["mute", "silent", "no sound", "strip sound"],
  },
  {
    title: "Add Audio",
    description: "Replace a video's audio with your own track",
    href: "/video/add-audio",
    icon: AddAudioIcon,
    category: "edit",
    colorClass: "tool-video-remove-audio",
    keywords: ["add audio", "replace audio", "add music", "soundtrack", "add sound", "audio over video"],
  },
  {
    title: "Rotate",
    description: "Turn a sideways video upright, without re-encoding",
    href: "/video/rotate",
    icon: VideoRotateIcon,
    category: "edit",
    colorClass: "tool-video-rotate",
    keywords: ["rotate", "turn", "sideways", "upside down", "90", "180", "portrait", "landscape", "rotate video"],
  },
  {
    title: "Flip",
    description: "Mirror a video left-to-right or top-to-bottom",
    href: "/video/flip",
    icon: VideoFlipIcon,
    category: "edit",
    colorClass: "tool-video-flip",
    keywords: [
      "flip",
      "mirror",
      "flip video",
      "mirror video",
      "flip horizontal",
      "flip vertical",
      "unmirror",
      "selfie",
      "front camera",
      "reverse image",
    ],
  },
  {
    title: "Change Speed",
    description: "Speed up or slow down a video",
    href: "/video/speed",
    icon: VideoSpeedIcon,
    category: "edit",
    colorClass: "tool-video-speed",
    keywords: [
      "speed",
      "slow motion",
      "slomo",
      "timelapse",
      "fast forward",
      "playback rate",
      "speed up video",
      "slow down video",
      "2x",
    ],
  },
  {
    title: "To GIF",
    description: "Convert video clips to animated GIFs",
    href: "/video/to-gif",
    icon: VideoToGifIcon,
    category: "convert",
    colorClass: "tool-video-to-gif",
    keywords: ["video to gif", "animated", "mp4 to gif", "loop"],
    io: { from: ["mp4", "mov", "mkv", "avi", "webm", "video"], to: ["gif"] },
  },
  {
    title: "Extract Audio",
    description: "Extract audio track from video",
    href: "/video/extract-audio",
    icon: ExtractIcon,
    category: "convert",
    colorClass: "tool-audio-extract",
    keywords: ["get audio", "rip audio", "video to mp3", "video to audio"],
    io: {
      from: ["mp4", "mov", "mkv", "avi", "webm", "video"],
      to: ["mp3", "wav", "m4a", "aac", "flac", "ogg", "audio"],
    },
  },
  {
    title: "Metadata",
    description: "View video file information",
    href: "/video/metadata",
    icon: VideoMetadataIcon,
    category: "info",
    colorClass: "tool-video-metadata",
    keywords: ["info", "details", "codec", "resolution", "duration", "fps"],
  },
  {
    title: "Merge",
    description: "Combine multiple videos into one",
    href: "/video/merge",
    icon: VideoMergeIcon,
    category: "edit",
    colorClass: "tool-video-merge",
    keywords: ["combine", "join", "concatenate", "stitch", "append", "splice"],
  },
  {
    title: "Subtitles",
    description: "Turn speech into timed, editable captions",
    href: "/caption",
    icon: CaptionIcon,
    category: "convert",
    colorClass: "tool-caption",
    keywords: [
      "subtitles",
      "captions",
      "cc",
      "srt",
      "vtt",
      "transcribe",
      "transcript",
      "speech to text",
      "auto caption",
      "closed captions",
      "dictation",
    ],
    io: {
      from: ["mp4", "mov", "mkv", "webm", "m4v", "mp3", "wav", "m4a", "aac", "flac", "ogg", "video", "audio"],
      to: ["srt", "vtt", "txt", "text"],
    },
  },
];

export const videoCategoryLabels: Record<string, string> = {
  optimize: "Optimize",
  edit: "Edit",
  convert: "Convert",
  info: "Info",
};
