/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XlsxToPdfRouteImport } from './routes/xlsx-to-pdf'
import { Route as WatermarkRouteImport } from './routes/watermark'
import { Route as TestCompressRouteImport } from './routes/test-compress'
import { Route as SplitRouteImport } from './routes/split'
import { Route as SignRouteImport } from './routes/sign'
import { Route as SanitizeRouteImport } from './routes/sanitize'
import { Route as RotateRouteImport } from './routes/rotate'
import { Route as ReverseRouteImport } from './routes/reverse'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PptxToPdfRouteImport } from './routes/pptx-to-pdf'
import { Route as PdfToTextRouteImport } from './routes/pdf-to-text'
import { Route as PdfToPdfaRouteImport } from './routes/pdf-to-pdfa'
import { Route as PdfToImagesRouteImport } from './routes/pdf-to-images'
import { Route as PdfToEpubRouteImport } from './routes/pdf-to-epub'
import { Route as PageNumbersRouteImport } from './routes/page-numbers'
import { Route as OrganizeRouteImport } from './routes/organize'
import { Route as OcrRouteImport } from './routes/ocr'
import { Route as MetadataRouteImport } from './routes/metadata'
import { Route as MergeRouteImport } from './routes/merge'
import { Route as MarkdownToPdfRouteImport } from './routes/markdown-to-pdf'
import { Route as ImagesToPdfRouteImport } from './routes/images-to-pdf'
import { Route as HtmlToPdfRouteImport } from './routes/html-to-pdf'
import { Route as GrayscaleRouteImport } from './routes/grayscale'
import { Route as ExtractImagesRouteImport } from './routes/extract-images'
import { Route as EncryptRouteImport } from './routes/encrypt'
import { Route as EditRouteImport } from './routes/edit'
import { Route as DuplicateRouteImport } from './routes/duplicate'
import { Route as DocxToPdfRouteImport } from './routes/docx-to-pdf'
import { Route as DeleteRouteImport } from './routes/delete'
import { Route as DecryptRouteImport } from './routes/decrypt'
import { Route as CompressRouteImport } from './routes/compress'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoIndexRouteImport } from './routes/video.index'
import { Route as QrIndexRouteImport } from './routes/qr.index'
import { Route as ImageIndexRouteImport } from './routes/image.index'
import { Route as AudioIndexRouteImport } from './routes/audio.index'
import { Route as VideoTrimRouteImport } from './routes/video.trim'
import { Route as VideoToGifRouteImport } from './routes/video.to-gif'
import { Route as VideoRotateRouteImport } from './routes/video.rotate'
import { Route as VideoResizeRouteImport } from './routes/video.resize'
import { Route as VideoRemoveAudioRouteImport } from './routes/video.remove-audio'
import { Route as VideoMetadataRouteImport } from './routes/video.metadata'
import { Route as VideoExtractAudioRouteImport } from './routes/video.extract-audio'
import { Route as VideoCropRouteImport } from './routes/video.crop'
import { Route as VideoConvertRouteImport } from './routes/video.convert'
import { Route as VideoCompressRouteImport } from './routes/video.compress'
import { Route as QrScanRouteImport } from './routes/qr.scan'
import { Route as QrGenerateRouteImport } from './routes/qr.generate'
import { Route as QrBulkRouteImport } from './routes/qr.bulk'
import { Route as QrBarcodeRouteImport } from './routes/qr.barcode'
import { Route as ImageWatermarkRouteImport } from './routes/image.watermark'
import { Route as ImageToBase64RouteImport } from './routes/image.to-base64'
import { Route as ImageStripMetadataRouteImport } from './routes/image.strip-metadata'
import { Route as ImageScreenshotRouteImport } from './routes/image.screenshot'
import { Route as ImageRotateRouteImport } from './routes/image.rotate'
import { Route as ImageResizeRouteImport } from './routes/image.resize'
import { Route as ImageRemoveBgRouteImport } from './routes/image.remove-bg'
import { Route as ImagePaletteRouteImport } from './routes/image.palette'
import { Route as ImageHeicToJpegRouteImport } from './routes/image.heic-to-jpeg'
import { Route as ImageFiltersRouteImport } from './routes/image.filters'
import { Route as ImageFaviconRouteImport } from './routes/image.favicon'
import { Route as ImageEditRouteImport } from './routes/image.edit'
import { Route as ImageCropRouteImport } from './routes/image.crop'
import { Route as ImageConvertRouteImport } from './routes/image.convert'
import { Route as ImageCompressRouteImport } from './routes/image.compress'
import { Route as ImageCollageRouteImport } from './routes/image.collage'
import { Route as ImageBorderRouteImport } from './routes/image.border'
import { Route as ImageBlurRouteImport } from './routes/image.blur'
import { Route as ImageAdjustRouteImport } from './routes/image.adjust'
import { Route as AudioWaveformRouteImport } from './routes/audio.waveform'
import { Route as AudioVolumeRouteImport } from './routes/audio.volume'
import { Route as AudioTrimRouteImport } from './routes/audio.trim'
import { Route as AudioSpeedRouteImport } from './routes/audio.speed'
import { Route as AudioReverseRouteImport } from './routes/audio.reverse'
import { Route as AudioRemoveSilenceRouteImport } from './routes/audio.remove-silence'
import { Route as AudioRecordRouteImport } from './routes/audio.record'
import { Route as AudioNormalizeRouteImport } from './routes/audio.normalize'
import { Route as AudioMetadataRouteImport } from './routes/audio.metadata'
import { Route as AudioMergeRouteImport } from './routes/audio.merge'
import { Route as AudioFadeRouteImport } from './routes/audio.fade'
import { Route as AudioDenoiseRouteImport } from './routes/audio.denoise'
import { Route as AudioConvertRouteImport } from './routes/audio.convert'
import { Route as AudioCompressRouteImport } from './routes/audio.compress'

const XlsxToPdfRoute = XlsxToPdfRouteImport.update({
  id: '/xlsx-to-pdf',
  path: '/xlsx-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const WatermarkRoute = WatermarkRouteImport.update({
  id: '/watermark',
  path: '/watermark',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCompressRoute = TestCompressRouteImport.update({
  id: '/test-compress',
  path: '/test-compress',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitRoute = SplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const SanitizeRoute = SanitizeRouteImport.update({
  id: '/sanitize',
  path: '/sanitize',
  getParentRoute: () => rootRouteImport,
} as any)
const RotateRoute = RotateRouteImport.update({
  id: '/rotate',
  path: '/rotate',
  getParentRoute: () => rootRouteImport,
} as any)
const ReverseRoute = ReverseRouteImport.update({
  id: '/reverse',
  path: '/reverse',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PptxToPdfRoute = PptxToPdfRouteImport.update({
  id: '/pptx-to-pdf',
  path: '/pptx-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToTextRoute = PdfToTextRouteImport.update({
  id: '/pdf-to-text',
  path: '/pdf-to-text',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToPdfaRoute = PdfToPdfaRouteImport.update({
  id: '/pdf-to-pdfa',
  path: '/pdf-to-pdfa',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToImagesRoute = PdfToImagesRouteImport.update({
  id: '/pdf-to-images',
  path: '/pdf-to-images',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToEpubRoute = PdfToEpubRouteImport.update({
  id: '/pdf-to-epub',
  path: '/pdf-to-epub',
  getParentRoute: () => rootRouteImport,
} as any)
const PageNumbersRoute = PageNumbersRouteImport.update({
  id: '/page-numbers',
  path: '/page-numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizeRoute = OrganizeRouteImport.update({
  id: '/organize',
  path: '/organize',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrRoute = OcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataRoute = MetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeRoute = MergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkdownToPdfRoute = MarkdownToPdfRouteImport.update({
  id: '/markdown-to-pdf',
  path: '/markdown-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesToPdfRoute = ImagesToPdfRouteImport.update({
  id: '/images-to-pdf',
  path: '/images-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlToPdfRoute = HtmlToPdfRouteImport.update({
  id: '/html-to-pdf',
  path: '/html-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const GrayscaleRoute = GrayscaleRouteImport.update({
  id: '/grayscale',
  path: '/grayscale',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractImagesRoute = ExtractImagesRouteImport.update({
  id: '/extract-images',
  path: '/extract-images',
  getParentRoute: () => rootRouteImport,
} as any)
const EncryptRoute = EncryptRouteImport.update({
  id: '/encrypt',
  path: '/encrypt',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicateRoute = DuplicateRouteImport.update({
  id: '/duplicate',
  path: '/duplicate',
  getParentRoute: () => rootRouteImport,
} as any)
const DocxToPdfRoute = DocxToPdfRouteImport.update({
  id: '/docx-to-pdf',
  path: '/docx-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteRoute = DeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const DecryptRoute = DecryptRouteImport.update({
  id: '/decrypt',
  path: '/decrypt',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressRoute = CompressRouteImport.update({
  id: '/compress',
  path: '/compress',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIndexRoute = VideoIndexRouteImport.update({
  id: '/video/',
  path: '/video/',
  getParentRoute: () => rootRouteImport,
} as any)
const QrIndexRoute = QrIndexRouteImport.update({
  id: '/qr/',
  path: '/qr/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageIndexRoute = ImageIndexRouteImport.update({
  id: '/image/',
  path: '/image/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioIndexRoute = AudioIndexRouteImport.update({
  id: '/audio/',
  path: '/audio/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoTrimRoute = VideoTrimRouteImport.update({
  id: '/video/trim',
  path: '/video/trim',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoToGifRoute = VideoToGifRouteImport.update({
  id: '/video/to-gif',
  path: '/video/to-gif',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRotateRoute = VideoRotateRouteImport.update({
  id: '/video/rotate',
  path: '/video/rotate',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoResizeRoute = VideoResizeRouteImport.update({
  id: '/video/resize',
  path: '/video/resize',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRemoveAudioRoute = VideoRemoveAudioRouteImport.update({
  id: '/video/remove-audio',
  path: '/video/remove-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoMetadataRoute = VideoMetadataRouteImport.update({
  id: '/video/metadata',
  path: '/video/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoExtractAudioRoute = VideoExtractAudioRouteImport.update({
  id: '/video/extract-audio',
  path: '/video/extract-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoCropRoute = VideoCropRouteImport.update({
  id: '/video/crop',
  path: '/video/crop',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoConvertRoute = VideoConvertRouteImport.update({
  id: '/video/convert',
  path: '/video/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoCompressRoute = VideoCompressRouteImport.update({
  id: '/video/compress',
  path: '/video/compress',
  getParentRoute: () => rootRouteImport,
} as any)
const QrScanRoute = QrScanRouteImport.update({
  id: '/qr/scan',
  path: '/qr/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const QrGenerateRoute = QrGenerateRouteImport.update({
  id: '/qr/generate',
  path: '/qr/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const QrBulkRoute = QrBulkRouteImport.update({
  id: '/qr/bulk',
  path: '/qr/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const QrBarcodeRoute = QrBarcodeRouteImport.update({
  id: '/qr/barcode',
  path: '/qr/barcode',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageWatermarkRoute = ImageWatermarkRouteImport.update({
  id: '/image/watermark',
  path: '/image/watermark',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToBase64Route = ImageToBase64RouteImport.update({
  id: '/image/to-base64',
  path: '/image/to-base64',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageStripMetadataRoute = ImageStripMetadataRouteImport.update({
  id: '/image/strip-metadata',
  path: '/image/strip-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageScreenshotRoute = ImageScreenshotRouteImport.update({
  id: '/image/screenshot',
  path: '/image/screenshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRotateRoute = ImageRotateRouteImport.update({
  id: '/image/rotate',
  path: '/image/rotate',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageResizeRoute = ImageResizeRouteImport.update({
  id: '/image/resize',
  path: '/image/resize',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRemoveBgRoute = ImageRemoveBgRouteImport.update({
  id: '/image/remove-bg',
  path: '/image/remove-bg',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagePaletteRoute = ImagePaletteRouteImport.update({
  id: '/image/palette',
  path: '/image/palette',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageHeicToJpegRoute = ImageHeicToJpegRouteImport.update({
  id: '/image/heic-to-jpeg',
  path: '/image/heic-to-jpeg',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageFiltersRoute = ImageFiltersRouteImport.update({
  id: '/image/filters',
  path: '/image/filters',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageFaviconRoute = ImageFaviconRouteImport.update({
  id: '/image/favicon',
  path: '/image/favicon',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageEditRoute = ImageEditRouteImport.update({
  id: '/image/edit',
  path: '/image/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCropRoute = ImageCropRouteImport.update({
  id: '/image/crop',
  path: '/image/crop',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageConvertRoute = ImageConvertRouteImport.update({
  id: '/image/convert',
  path: '/image/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCompressRoute = ImageCompressRouteImport.update({
  id: '/image/compress',
  path: '/image/compress',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCollageRoute = ImageCollageRouteImport.update({
  id: '/image/collage',
  path: '/image/collage',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageBorderRoute = ImageBorderRouteImport.update({
  id: '/image/border',
  path: '/image/border',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageBlurRoute = ImageBlurRouteImport.update({
  id: '/image/blur',
  path: '/image/blur',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageAdjustRoute = ImageAdjustRouteImport.update({
  id: '/image/adjust',
  path: '/image/adjust',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioWaveformRoute = AudioWaveformRouteImport.update({
  id: '/audio/waveform',
  path: '/audio/waveform',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioVolumeRoute = AudioVolumeRouteImport.update({
  id: '/audio/volume',
  path: '/audio/volume',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioTrimRoute = AudioTrimRouteImport.update({
  id: '/audio/trim',
  path: '/audio/trim',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioSpeedRoute = AudioSpeedRouteImport.update({
  id: '/audio/speed',
  path: '/audio/speed',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioReverseRoute = AudioReverseRouteImport.update({
  id: '/audio/reverse',
  path: '/audio/reverse',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRemoveSilenceRoute = AudioRemoveSilenceRouteImport.update({
  id: '/audio/remove-silence',
  path: '/audio/remove-silence',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRecordRoute = AudioRecordRouteImport.update({
  id: '/audio/record',
  path: '/audio/record',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioNormalizeRoute = AudioNormalizeRouteImport.update({
  id: '/audio/normalize',
  path: '/audio/normalize',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioMetadataRoute = AudioMetadataRouteImport.update({
  id: '/audio/metadata',
  path: '/audio/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioMergeRoute = AudioMergeRouteImport.update({
  id: '/audio/merge',
  path: '/audio/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioFadeRoute = AudioFadeRouteImport.update({
  id: '/audio/fade',
  path: '/audio/fade',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioDenoiseRoute = AudioDenoiseRouteImport.update({
  id: '/audio/denoise',
  path: '/audio/denoise',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioConvertRoute = AudioConvertRouteImport.update({
  id: '/audio/convert',
  path: '/audio/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioCompressRoute = AudioCompressRouteImport.update({
  id: '/audio/compress',
  path: '/audio/compress',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/decrypt': typeof DecryptRoute
  '/delete': typeof DeleteRoute
  '/docx-to-pdf': typeof DocxToPdfRoute
  '/duplicate': typeof DuplicateRoute
  '/edit': typeof EditRoute
  '/encrypt': typeof EncryptRoute
  '/extract-images': typeof ExtractImagesRoute
  '/grayscale': typeof GrayscaleRoute
  '/html-to-pdf': typeof HtmlToPdfRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/markdown-to-pdf': typeof MarkdownToPdfRoute
  '/merge': typeof MergeRoute
  '/metadata': typeof MetadataRoute
  '/ocr': typeof OcrRoute
  '/organize': typeof OrganizeRoute
  '/page-numbers': typeof PageNumbersRoute
  '/pdf-to-epub': typeof PdfToEpubRoute
  '/pdf-to-images': typeof PdfToImagesRoute
  '/pdf-to-pdfa': typeof PdfToPdfaRoute
  '/pdf-to-text': typeof PdfToTextRoute
  '/pptx-to-pdf': typeof PptxToPdfRoute
  '/privacy': typeof PrivacyRoute
  '/reverse': typeof ReverseRoute
  '/rotate': typeof RotateRoute
  '/sanitize': typeof SanitizeRoute
  '/sign': typeof SignRoute
  '/split': typeof SplitRoute
  '/test-compress': typeof TestCompressRoute
  '/watermark': typeof WatermarkRoute
  '/xlsx-to-pdf': typeof XlsxToPdfRoute
  '/audio/compress': typeof AudioCompressRoute
  '/audio/convert': typeof AudioConvertRoute
  '/audio/denoise': typeof AudioDenoiseRoute
  '/audio/fade': typeof AudioFadeRoute
  '/audio/merge': typeof AudioMergeRoute
  '/audio/metadata': typeof AudioMetadataRoute
  '/audio/normalize': typeof AudioNormalizeRoute
  '/audio/record': typeof AudioRecordRoute
  '/audio/remove-silence': typeof AudioRemoveSilenceRoute
  '/audio/reverse': typeof AudioReverseRoute
  '/audio/speed': typeof AudioSpeedRoute
  '/audio/trim': typeof AudioTrimRoute
  '/audio/volume': typeof AudioVolumeRoute
  '/audio/waveform': typeof AudioWaveformRoute
  '/image/adjust': typeof ImageAdjustRoute
  '/image/blur': typeof ImageBlurRoute
  '/image/border': typeof ImageBorderRoute
  '/image/collage': typeof ImageCollageRoute
  '/image/compress': typeof ImageCompressRoute
  '/image/convert': typeof ImageConvertRoute
  '/image/crop': typeof ImageCropRoute
  '/image/edit': typeof ImageEditRoute
  '/image/favicon': typeof ImageFaviconRoute
  '/image/filters': typeof ImageFiltersRoute
  '/image/heic-to-jpeg': typeof ImageHeicToJpegRoute
  '/image/palette': typeof ImagePaletteRoute
  '/image/remove-bg': typeof ImageRemoveBgRoute
  '/image/resize': typeof ImageResizeRoute
  '/image/rotate': typeof ImageRotateRoute
  '/image/screenshot': typeof ImageScreenshotRoute
  '/image/strip-metadata': typeof ImageStripMetadataRoute
  '/image/to-base64': typeof ImageToBase64Route
  '/image/watermark': typeof ImageWatermarkRoute
  '/qr/barcode': typeof QrBarcodeRoute
  '/qr/bulk': typeof QrBulkRoute
  '/qr/generate': typeof QrGenerateRoute
  '/qr/scan': typeof QrScanRoute
  '/video/compress': typeof VideoCompressRoute
  '/video/convert': typeof VideoConvertRoute
  '/video/crop': typeof VideoCropRoute
  '/video/extract-audio': typeof VideoExtractAudioRoute
  '/video/metadata': typeof VideoMetadataRoute
  '/video/remove-audio': typeof VideoRemoveAudioRoute
  '/video/resize': typeof VideoResizeRoute
  '/video/rotate': typeof VideoRotateRoute
  '/video/to-gif': typeof VideoToGifRoute
  '/video/trim': typeof VideoTrimRoute
  '/audio/': typeof AudioIndexRoute
  '/image/': typeof ImageIndexRoute
  '/qr/': typeof QrIndexRoute
  '/video/': typeof VideoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/decrypt': typeof DecryptRoute
  '/delete': typeof DeleteRoute
  '/docx-to-pdf': typeof DocxToPdfRoute
  '/duplicate': typeof DuplicateRoute
  '/edit': typeof EditRoute
  '/encrypt': typeof EncryptRoute
  '/extract-images': typeof ExtractImagesRoute
  '/grayscale': typeof GrayscaleRoute
  '/html-to-pdf': typeof HtmlToPdfRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/markdown-to-pdf': typeof MarkdownToPdfRoute
  '/merge': typeof MergeRoute
  '/metadata': typeof MetadataRoute
  '/ocr': typeof OcrRoute
  '/organize': typeof OrganizeRoute
  '/page-numbers': typeof PageNumbersRoute
  '/pdf-to-epub': typeof PdfToEpubRoute
  '/pdf-to-images': typeof PdfToImagesRoute
  '/pdf-to-pdfa': typeof PdfToPdfaRoute
  '/pdf-to-text': typeof PdfToTextRoute
  '/pptx-to-pdf': typeof PptxToPdfRoute
  '/privacy': typeof PrivacyRoute
  '/reverse': typeof ReverseRoute
  '/rotate': typeof RotateRoute
  '/sanitize': typeof SanitizeRoute
  '/sign': typeof SignRoute
  '/split': typeof SplitRoute
  '/test-compress': typeof TestCompressRoute
  '/watermark': typeof WatermarkRoute
  '/xlsx-to-pdf': typeof XlsxToPdfRoute
  '/audio/compress': typeof AudioCompressRoute
  '/audio/convert': typeof AudioConvertRoute
  '/audio/denoise': typeof AudioDenoiseRoute
  '/audio/fade': typeof AudioFadeRoute
  '/audio/merge': typeof AudioMergeRoute
  '/audio/metadata': typeof AudioMetadataRoute
  '/audio/normalize': typeof AudioNormalizeRoute
  '/audio/record': typeof AudioRecordRoute
  '/audio/remove-silence': typeof AudioRemoveSilenceRoute
  '/audio/reverse': typeof AudioReverseRoute
  '/audio/speed': typeof AudioSpeedRoute
  '/audio/trim': typeof AudioTrimRoute
  '/audio/volume': typeof AudioVolumeRoute
  '/audio/waveform': typeof AudioWaveformRoute
  '/image/adjust': typeof ImageAdjustRoute
  '/image/blur': typeof ImageBlurRoute
  '/image/border': typeof ImageBorderRoute
  '/image/collage': typeof ImageCollageRoute
  '/image/compress': typeof ImageCompressRoute
  '/image/convert': typeof ImageConvertRoute
  '/image/crop': typeof ImageCropRoute
  '/image/edit': typeof ImageEditRoute
  '/image/favicon': typeof ImageFaviconRoute
  '/image/filters': typeof ImageFiltersRoute
  '/image/heic-to-jpeg': typeof ImageHeicToJpegRoute
  '/image/palette': typeof ImagePaletteRoute
  '/image/remove-bg': typeof ImageRemoveBgRoute
  '/image/resize': typeof ImageResizeRoute
  '/image/rotate': typeof ImageRotateRoute
  '/image/screenshot': typeof ImageScreenshotRoute
  '/image/strip-metadata': typeof ImageStripMetadataRoute
  '/image/to-base64': typeof ImageToBase64Route
  '/image/watermark': typeof ImageWatermarkRoute
  '/qr/barcode': typeof QrBarcodeRoute
  '/qr/bulk': typeof QrBulkRoute
  '/qr/generate': typeof QrGenerateRoute
  '/qr/scan': typeof QrScanRoute
  '/video/compress': typeof VideoCompressRoute
  '/video/convert': typeof VideoConvertRoute
  '/video/crop': typeof VideoCropRoute
  '/video/extract-audio': typeof VideoExtractAudioRoute
  '/video/metadata': typeof VideoMetadataRoute
  '/video/remove-audio': typeof VideoRemoveAudioRoute
  '/video/resize': typeof VideoResizeRoute
  '/video/rotate': typeof VideoRotateRoute
  '/video/to-gif': typeof VideoToGifRoute
  '/video/trim': typeof VideoTrimRoute
  '/audio': typeof AudioIndexRoute
  '/image': typeof ImageIndexRoute
  '/qr': typeof QrIndexRoute
  '/video': typeof VideoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/decrypt': typeof DecryptRoute
  '/delete': typeof DeleteRoute
  '/docx-to-pdf': typeof DocxToPdfRoute
  '/duplicate': typeof DuplicateRoute
  '/edit': typeof EditRoute
  '/encrypt': typeof EncryptRoute
  '/extract-images': typeof ExtractImagesRoute
  '/grayscale': typeof GrayscaleRoute
  '/html-to-pdf': typeof HtmlToPdfRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/markdown-to-pdf': typeof MarkdownToPdfRoute
  '/merge': typeof MergeRoute
  '/metadata': typeof MetadataRoute
  '/ocr': typeof OcrRoute
  '/organize': typeof OrganizeRoute
  '/page-numbers': typeof PageNumbersRoute
  '/pdf-to-epub': typeof PdfToEpubRoute
  '/pdf-to-images': typeof PdfToImagesRoute
  '/pdf-to-pdfa': typeof PdfToPdfaRoute
  '/pdf-to-text': typeof PdfToTextRoute
  '/pptx-to-pdf': typeof PptxToPdfRoute
  '/privacy': typeof PrivacyRoute
  '/reverse': typeof ReverseRoute
  '/rotate': typeof RotateRoute
  '/sanitize': typeof SanitizeRoute
  '/sign': typeof SignRoute
  '/split': typeof SplitRoute
  '/test-compress': typeof TestCompressRoute
  '/watermark': typeof WatermarkRoute
  '/xlsx-to-pdf': typeof XlsxToPdfRoute
  '/audio/compress': typeof AudioCompressRoute
  '/audio/convert': typeof AudioConvertRoute
  '/audio/denoise': typeof AudioDenoiseRoute
  '/audio/fade': typeof AudioFadeRoute
  '/audio/merge': typeof AudioMergeRoute
  '/audio/metadata': typeof AudioMetadataRoute
  '/audio/normalize': typeof AudioNormalizeRoute
  '/audio/record': typeof AudioRecordRoute
  '/audio/remove-silence': typeof AudioRemoveSilenceRoute
  '/audio/reverse': typeof AudioReverseRoute
  '/audio/speed': typeof AudioSpeedRoute
  '/audio/trim': typeof AudioTrimRoute
  '/audio/volume': typeof AudioVolumeRoute
  '/audio/waveform': typeof AudioWaveformRoute
  '/image/adjust': typeof ImageAdjustRoute
  '/image/blur': typeof ImageBlurRoute
  '/image/border': typeof ImageBorderRoute
  '/image/collage': typeof ImageCollageRoute
  '/image/compress': typeof ImageCompressRoute
  '/image/convert': typeof ImageConvertRoute
  '/image/crop': typeof ImageCropRoute
  '/image/edit': typeof ImageEditRoute
  '/image/favicon': typeof ImageFaviconRoute
  '/image/filters': typeof ImageFiltersRoute
  '/image/heic-to-jpeg': typeof ImageHeicToJpegRoute
  '/image/palette': typeof ImagePaletteRoute
  '/image/remove-bg': typeof ImageRemoveBgRoute
  '/image/resize': typeof ImageResizeRoute
  '/image/rotate': typeof ImageRotateRoute
  '/image/screenshot': typeof ImageScreenshotRoute
  '/image/strip-metadata': typeof ImageStripMetadataRoute
  '/image/to-base64': typeof ImageToBase64Route
  '/image/watermark': typeof ImageWatermarkRoute
  '/qr/barcode': typeof QrBarcodeRoute
  '/qr/bulk': typeof QrBulkRoute
  '/qr/generate': typeof QrGenerateRoute
  '/qr/scan': typeof QrScanRoute
  '/video/compress': typeof VideoCompressRoute
  '/video/convert': typeof VideoConvertRoute
  '/video/crop': typeof VideoCropRoute
  '/video/extract-audio': typeof VideoExtractAudioRoute
  '/video/metadata': typeof VideoMetadataRoute
  '/video/remove-audio': typeof VideoRemoveAudioRoute
  '/video/resize': typeof VideoResizeRoute
  '/video/rotate': typeof VideoRotateRoute
  '/video/to-gif': typeof VideoToGifRoute
  '/video/trim': typeof VideoTrimRoute
  '/audio/': typeof AudioIndexRoute
  '/image/': typeof ImageIndexRoute
  '/qr/': typeof QrIndexRoute
  '/video/': typeof VideoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compress'
    | '/decrypt'
    | '/delete'
    | '/docx-to-pdf'
    | '/duplicate'
    | '/edit'
    | '/encrypt'
    | '/extract-images'
    | '/grayscale'
    | '/html-to-pdf'
    | '/images-to-pdf'
    | '/markdown-to-pdf'
    | '/merge'
    | '/metadata'
    | '/ocr'
    | '/organize'
    | '/page-numbers'
    | '/pdf-to-epub'
    | '/pdf-to-images'
    | '/pdf-to-pdfa'
    | '/pdf-to-text'
    | '/pptx-to-pdf'
    | '/privacy'
    | '/reverse'
    | '/rotate'
    | '/sanitize'
    | '/sign'
    | '/split'
    | '/test-compress'
    | '/watermark'
    | '/xlsx-to-pdf'
    | '/audio/compress'
    | '/audio/convert'
    | '/audio/denoise'
    | '/audio/fade'
    | '/audio/merge'
    | '/audio/metadata'
    | '/audio/normalize'
    | '/audio/record'
    | '/audio/remove-silence'
    | '/audio/reverse'
    | '/audio/speed'
    | '/audio/trim'
    | '/audio/volume'
    | '/audio/waveform'
    | '/image/adjust'
    | '/image/blur'
    | '/image/border'
    | '/image/collage'
    | '/image/compress'
    | '/image/convert'
    | '/image/crop'
    | '/image/edit'
    | '/image/favicon'
    | '/image/filters'
    | '/image/heic-to-jpeg'
    | '/image/palette'
    | '/image/remove-bg'
    | '/image/resize'
    | '/image/rotate'
    | '/image/screenshot'
    | '/image/strip-metadata'
    | '/image/to-base64'
    | '/image/watermark'
    | '/qr/barcode'
    | '/qr/bulk'
    | '/qr/generate'
    | '/qr/scan'
    | '/video/compress'
    | '/video/convert'
    | '/video/crop'
    | '/video/extract-audio'
    | '/video/metadata'
    | '/video/remove-audio'
    | '/video/resize'
    | '/video/rotate'
    | '/video/to-gif'
    | '/video/trim'
    | '/audio/'
    | '/image/'
    | '/qr/'
    | '/video/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compress'
    | '/decrypt'
    | '/delete'
    | '/docx-to-pdf'
    | '/duplicate'
    | '/edit'
    | '/encrypt'
    | '/extract-images'
    | '/grayscale'
    | '/html-to-pdf'
    | '/images-to-pdf'
    | '/markdown-to-pdf'
    | '/merge'
    | '/metadata'
    | '/ocr'
    | '/organize'
    | '/page-numbers'
    | '/pdf-to-epub'
    | '/pdf-to-images'
    | '/pdf-to-pdfa'
    | '/pdf-to-text'
    | '/pptx-to-pdf'
    | '/privacy'
    | '/reverse'
    | '/rotate'
    | '/sanitize'
    | '/sign'
    | '/split'
    | '/test-compress'
    | '/watermark'
    | '/xlsx-to-pdf'
    | '/audio/compress'
    | '/audio/convert'
    | '/audio/denoise'
    | '/audio/fade'
    | '/audio/merge'
    | '/audio/metadata'
    | '/audio/normalize'
    | '/audio/record'
    | '/audio/remove-silence'
    | '/audio/reverse'
    | '/audio/speed'
    | '/audio/trim'
    | '/audio/volume'
    | '/audio/waveform'
    | '/image/adjust'
    | '/image/blur'
    | '/image/border'
    | '/image/collage'
    | '/image/compress'
    | '/image/convert'
    | '/image/crop'
    | '/image/edit'
    | '/image/favicon'
    | '/image/filters'
    | '/image/heic-to-jpeg'
    | '/image/palette'
    | '/image/remove-bg'
    | '/image/resize'
    | '/image/rotate'
    | '/image/screenshot'
    | '/image/strip-metadata'
    | '/image/to-base64'
    | '/image/watermark'
    | '/qr/barcode'
    | '/qr/bulk'
    | '/qr/generate'
    | '/qr/scan'
    | '/video/compress'
    | '/video/convert'
    | '/video/crop'
    | '/video/extract-audio'
    | '/video/metadata'
    | '/video/remove-audio'
    | '/video/resize'
    | '/video/rotate'
    | '/video/to-gif'
    | '/video/trim'
    | '/audio'
    | '/image'
    | '/qr'
    | '/video'
  id:
    | '__root__'
    | '/'
    | '/compress'
    | '/decrypt'
    | '/delete'
    | '/docx-to-pdf'
    | '/duplicate'
    | '/edit'
    | '/encrypt'
    | '/extract-images'
    | '/grayscale'
    | '/html-to-pdf'
    | '/images-to-pdf'
    | '/markdown-to-pdf'
    | '/merge'
    | '/metadata'
    | '/ocr'
    | '/organize'
    | '/page-numbers'
    | '/pdf-to-epub'
    | '/pdf-to-images'
    | '/pdf-to-pdfa'
    | '/pdf-to-text'
    | '/pptx-to-pdf'
    | '/privacy'
    | '/reverse'
    | '/rotate'
    | '/sanitize'
    | '/sign'
    | '/split'
    | '/test-compress'
    | '/watermark'
    | '/xlsx-to-pdf'
    | '/audio/compress'
    | '/audio/convert'
    | '/audio/denoise'
    | '/audio/fade'
    | '/audio/merge'
    | '/audio/metadata'
    | '/audio/normalize'
    | '/audio/record'
    | '/audio/remove-silence'
    | '/audio/reverse'
    | '/audio/speed'
    | '/audio/trim'
    | '/audio/volume'
    | '/audio/waveform'
    | '/image/adjust'
    | '/image/blur'
    | '/image/border'
    | '/image/collage'
    | '/image/compress'
    | '/image/convert'
    | '/image/crop'
    | '/image/edit'
    | '/image/favicon'
    | '/image/filters'
    | '/image/heic-to-jpeg'
    | '/image/palette'
    | '/image/remove-bg'
    | '/image/resize'
    | '/image/rotate'
    | '/image/screenshot'
    | '/image/strip-metadata'
    | '/image/to-base64'
    | '/image/watermark'
    | '/qr/barcode'
    | '/qr/bulk'
    | '/qr/generate'
    | '/qr/scan'
    | '/video/compress'
    | '/video/convert'
    | '/video/crop'
    | '/video/extract-audio'
    | '/video/metadata'
    | '/video/remove-audio'
    | '/video/resize'
    | '/video/rotate'
    | '/video/to-gif'
    | '/video/trim'
    | '/audio/'
    | '/image/'
    | '/qr/'
    | '/video/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompressRoute: typeof CompressRoute
  DecryptRoute: typeof DecryptRoute
  DeleteRoute: typeof DeleteRoute
  DocxToPdfRoute: typeof DocxToPdfRoute
  DuplicateRoute: typeof DuplicateRoute
  EditRoute: typeof EditRoute
  EncryptRoute: typeof EncryptRoute
  ExtractImagesRoute: typeof ExtractImagesRoute
  GrayscaleRoute: typeof GrayscaleRoute
  HtmlToPdfRoute: typeof HtmlToPdfRoute
  ImagesToPdfRoute: typeof ImagesToPdfRoute
  MarkdownToPdfRoute: typeof MarkdownToPdfRoute
  MergeRoute: typeof MergeRoute
  MetadataRoute: typeof MetadataRoute
  OcrRoute: typeof OcrRoute
  OrganizeRoute: typeof OrganizeRoute
  PageNumbersRoute: typeof PageNumbersRoute
  PdfToEpubRoute: typeof PdfToEpubRoute
  PdfToImagesRoute: typeof PdfToImagesRoute
  PdfToPdfaRoute: typeof PdfToPdfaRoute
  PdfToTextRoute: typeof PdfToTextRoute
  PptxToPdfRoute: typeof PptxToPdfRoute
  PrivacyRoute: typeof PrivacyRoute
  ReverseRoute: typeof ReverseRoute
  RotateRoute: typeof RotateRoute
  SanitizeRoute: typeof SanitizeRoute
  SignRoute: typeof SignRoute
  SplitRoute: typeof SplitRoute
  TestCompressRoute: typeof TestCompressRoute
  WatermarkRoute: typeof WatermarkRoute
  XlsxToPdfRoute: typeof XlsxToPdfRoute
  AudioCompressRoute: typeof AudioCompressRoute
  AudioConvertRoute: typeof AudioConvertRoute
  AudioDenoiseRoute: typeof AudioDenoiseRoute
  AudioFadeRoute: typeof AudioFadeRoute
  AudioMergeRoute: typeof AudioMergeRoute
  AudioMetadataRoute: typeof AudioMetadataRoute
  AudioNormalizeRoute: typeof AudioNormalizeRoute
  AudioRecordRoute: typeof AudioRecordRoute
  AudioRemoveSilenceRoute: typeof AudioRemoveSilenceRoute
  AudioReverseRoute: typeof AudioReverseRoute
  AudioSpeedRoute: typeof AudioSpeedRoute
  AudioTrimRoute: typeof AudioTrimRoute
  AudioVolumeRoute: typeof AudioVolumeRoute
  AudioWaveformRoute: typeof AudioWaveformRoute
  ImageAdjustRoute: typeof ImageAdjustRoute
  ImageBlurRoute: typeof ImageBlurRoute
  ImageBorderRoute: typeof ImageBorderRoute
  ImageCollageRoute: typeof ImageCollageRoute
  ImageCompressRoute: typeof ImageCompressRoute
  ImageConvertRoute: typeof ImageConvertRoute
  ImageCropRoute: typeof ImageCropRoute
  ImageEditRoute: typeof ImageEditRoute
  ImageFaviconRoute: typeof ImageFaviconRoute
  ImageFiltersRoute: typeof ImageFiltersRoute
  ImageHeicToJpegRoute: typeof ImageHeicToJpegRoute
  ImagePaletteRoute: typeof ImagePaletteRoute
  ImageRemoveBgRoute: typeof ImageRemoveBgRoute
  ImageResizeRoute: typeof ImageResizeRoute
  ImageRotateRoute: typeof ImageRotateRoute
  ImageScreenshotRoute: typeof ImageScreenshotRoute
  ImageStripMetadataRoute: typeof ImageStripMetadataRoute
  ImageToBase64Route: typeof ImageToBase64Route
  ImageWatermarkRoute: typeof ImageWatermarkRoute
  QrBarcodeRoute: typeof QrBarcodeRoute
  QrBulkRoute: typeof QrBulkRoute
  QrGenerateRoute: typeof QrGenerateRoute
  QrScanRoute: typeof QrScanRoute
  VideoCompressRoute: typeof VideoCompressRoute
  VideoConvertRoute: typeof VideoConvertRoute
  VideoCropRoute: typeof VideoCropRoute
  VideoExtractAudioRoute: typeof VideoExtractAudioRoute
  VideoMetadataRoute: typeof VideoMetadataRoute
  VideoRemoveAudioRoute: typeof VideoRemoveAudioRoute
  VideoResizeRoute: typeof VideoResizeRoute
  VideoRotateRoute: typeof VideoRotateRoute
  VideoToGifRoute: typeof VideoToGifRoute
  VideoTrimRoute: typeof VideoTrimRoute
  AudioIndexRoute: typeof AudioIndexRoute
  ImageIndexRoute: typeof ImageIndexRoute
  QrIndexRoute: typeof QrIndexRoute
  VideoIndexRoute: typeof VideoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xlsx-to-pdf': {
      id: '/xlsx-to-pdf'
      path: '/xlsx-to-pdf'
      fullPath: '/xlsx-to-pdf'
      preLoaderRoute: typeof XlsxToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watermark': {
      id: '/watermark'
      path: '/watermark'
      fullPath: '/watermark'
      preLoaderRoute: typeof WatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-compress': {
      id: '/test-compress'
      path: '/test-compress'
      fullPath: '/test-compress'
      preLoaderRoute: typeof TestCompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split': {
      id: '/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof SplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanitize': {
      id: '/sanitize'
      path: '/sanitize'
      fullPath: '/sanitize'
      preLoaderRoute: typeof SanitizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotate': {
      id: '/rotate'
      path: '/rotate'
      fullPath: '/rotate'
      preLoaderRoute: typeof RotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reverse': {
      id: '/reverse'
      path: '/reverse'
      fullPath: '/reverse'
      preLoaderRoute: typeof ReverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pptx-to-pdf': {
      id: '/pptx-to-pdf'
      path: '/pptx-to-pdf'
      fullPath: '/pptx-to-pdf'
      preLoaderRoute: typeof PptxToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-text': {
      id: '/pdf-to-text'
      path: '/pdf-to-text'
      fullPath: '/pdf-to-text'
      preLoaderRoute: typeof PdfToTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-pdfa': {
      id: '/pdf-to-pdfa'
      path: '/pdf-to-pdfa'
      fullPath: '/pdf-to-pdfa'
      preLoaderRoute: typeof PdfToPdfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-images': {
      id: '/pdf-to-images'
      path: '/pdf-to-images'
      fullPath: '/pdf-to-images'
      preLoaderRoute: typeof PdfToImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-epub': {
      id: '/pdf-to-epub'
      path: '/pdf-to-epub'
      fullPath: '/pdf-to-epub'
      preLoaderRoute: typeof PdfToEpubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-numbers': {
      id: '/page-numbers'
      path: '/page-numbers'
      fullPath: '/page-numbers'
      preLoaderRoute: typeof PageNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organize': {
      id: '/organize'
      path: '/organize'
      fullPath: '/organize'
      preLoaderRoute: typeof OrganizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr': {
      id: '/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof OcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata': {
      id: '/metadata'
      path: '/metadata'
      fullPath: '/metadata'
      preLoaderRoute: typeof MetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge': {
      id: '/merge'
      path: '/merge'
      fullPath: '/merge'
      preLoaderRoute: typeof MergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markdown-to-pdf': {
      id: '/markdown-to-pdf'
      path: '/markdown-to-pdf'
      fullPath: '/markdown-to-pdf'
      preLoaderRoute: typeof MarkdownToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images-to-pdf': {
      id: '/images-to-pdf'
      path: '/images-to-pdf'
      fullPath: '/images-to-pdf'
      preLoaderRoute: typeof ImagesToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html-to-pdf': {
      id: '/html-to-pdf'
      path: '/html-to-pdf'
      fullPath: '/html-to-pdf'
      preLoaderRoute: typeof HtmlToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grayscale': {
      id: '/grayscale'
      path: '/grayscale'
      fullPath: '/grayscale'
      preLoaderRoute: typeof GrayscaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract-images': {
      id: '/extract-images'
      path: '/extract-images'
      fullPath: '/extract-images'
      preLoaderRoute: typeof ExtractImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encrypt': {
      id: '/encrypt'
      path: '/encrypt'
      fullPath: '/encrypt'
      preLoaderRoute: typeof EncryptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicate': {
      id: '/duplicate'
      path: '/duplicate'
      fullPath: '/duplicate'
      preLoaderRoute: typeof DuplicateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docx-to-pdf': {
      id: '/docx-to-pdf'
      path: '/docx-to-pdf'
      fullPath: '/docx-to-pdf'
      preLoaderRoute: typeof DocxToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete': {
      id: '/delete'
      path: '/delete'
      fullPath: '/delete'
      preLoaderRoute: typeof DeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decrypt': {
      id: '/decrypt'
      path: '/decrypt'
      fullPath: '/decrypt'
      preLoaderRoute: typeof DecryptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress': {
      id: '/compress'
      path: '/compress'
      fullPath: '/compress'
      preLoaderRoute: typeof CompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/': {
      id: '/video/'
      path: '/video'
      fullPath: '/video/'
      preLoaderRoute: typeof VideoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/': {
      id: '/qr/'
      path: '/qr'
      fullPath: '/qr/'
      preLoaderRoute: typeof QrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/': {
      id: '/image/'
      path: '/image'
      fullPath: '/image/'
      preLoaderRoute: typeof ImageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/': {
      id: '/audio/'
      path: '/audio'
      fullPath: '/audio/'
      preLoaderRoute: typeof AudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/trim': {
      id: '/video/trim'
      path: '/video/trim'
      fullPath: '/video/trim'
      preLoaderRoute: typeof VideoTrimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/to-gif': {
      id: '/video/to-gif'
      path: '/video/to-gif'
      fullPath: '/video/to-gif'
      preLoaderRoute: typeof VideoToGifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/rotate': {
      id: '/video/rotate'
      path: '/video/rotate'
      fullPath: '/video/rotate'
      preLoaderRoute: typeof VideoRotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/resize': {
      id: '/video/resize'
      path: '/video/resize'
      fullPath: '/video/resize'
      preLoaderRoute: typeof VideoResizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/remove-audio': {
      id: '/video/remove-audio'
      path: '/video/remove-audio'
      fullPath: '/video/remove-audio'
      preLoaderRoute: typeof VideoRemoveAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/metadata': {
      id: '/video/metadata'
      path: '/video/metadata'
      fullPath: '/video/metadata'
      preLoaderRoute: typeof VideoMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/extract-audio': {
      id: '/video/extract-audio'
      path: '/video/extract-audio'
      fullPath: '/video/extract-audio'
      preLoaderRoute: typeof VideoExtractAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/crop': {
      id: '/video/crop'
      path: '/video/crop'
      fullPath: '/video/crop'
      preLoaderRoute: typeof VideoCropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/convert': {
      id: '/video/convert'
      path: '/video/convert'
      fullPath: '/video/convert'
      preLoaderRoute: typeof VideoConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/compress': {
      id: '/video/compress'
      path: '/video/compress'
      fullPath: '/video/compress'
      preLoaderRoute: typeof VideoCompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/scan': {
      id: '/qr/scan'
      path: '/qr/scan'
      fullPath: '/qr/scan'
      preLoaderRoute: typeof QrScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/generate': {
      id: '/qr/generate'
      path: '/qr/generate'
      fullPath: '/qr/generate'
      preLoaderRoute: typeof QrGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/bulk': {
      id: '/qr/bulk'
      path: '/qr/bulk'
      fullPath: '/qr/bulk'
      preLoaderRoute: typeof QrBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/barcode': {
      id: '/qr/barcode'
      path: '/qr/barcode'
      fullPath: '/qr/barcode'
      preLoaderRoute: typeof QrBarcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/watermark': {
      id: '/image/watermark'
      path: '/image/watermark'
      fullPath: '/image/watermark'
      preLoaderRoute: typeof ImageWatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/to-base64': {
      id: '/image/to-base64'
      path: '/image/to-base64'
      fullPath: '/image/to-base64'
      preLoaderRoute: typeof ImageToBase64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/strip-metadata': {
      id: '/image/strip-metadata'
      path: '/image/strip-metadata'
      fullPath: '/image/strip-metadata'
      preLoaderRoute: typeof ImageStripMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/screenshot': {
      id: '/image/screenshot'
      path: '/image/screenshot'
      fullPath: '/image/screenshot'
      preLoaderRoute: typeof ImageScreenshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/rotate': {
      id: '/image/rotate'
      path: '/image/rotate'
      fullPath: '/image/rotate'
      preLoaderRoute: typeof ImageRotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/resize': {
      id: '/image/resize'
      path: '/image/resize'
      fullPath: '/image/resize'
      preLoaderRoute: typeof ImageResizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/remove-bg': {
      id: '/image/remove-bg'
      path: '/image/remove-bg'
      fullPath: '/image/remove-bg'
      preLoaderRoute: typeof ImageRemoveBgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/palette': {
      id: '/image/palette'
      path: '/image/palette'
      fullPath: '/image/palette'
      preLoaderRoute: typeof ImagePaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/heic-to-jpeg': {
      id: '/image/heic-to-jpeg'
      path: '/image/heic-to-jpeg'
      fullPath: '/image/heic-to-jpeg'
      preLoaderRoute: typeof ImageHeicToJpegRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/filters': {
      id: '/image/filters'
      path: '/image/filters'
      fullPath: '/image/filters'
      preLoaderRoute: typeof ImageFiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/favicon': {
      id: '/image/favicon'
      path: '/image/favicon'
      fullPath: '/image/favicon'
      preLoaderRoute: typeof ImageFaviconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/edit': {
      id: '/image/edit'
      path: '/image/edit'
      fullPath: '/image/edit'
      preLoaderRoute: typeof ImageEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/crop': {
      id: '/image/crop'
      path: '/image/crop'
      fullPath: '/image/crop'
      preLoaderRoute: typeof ImageCropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/convert': {
      id: '/image/convert'
      path: '/image/convert'
      fullPath: '/image/convert'
      preLoaderRoute: typeof ImageConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/compress': {
      id: '/image/compress'
      path: '/image/compress'
      fullPath: '/image/compress'
      preLoaderRoute: typeof ImageCompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/collage': {
      id: '/image/collage'
      path: '/image/collage'
      fullPath: '/image/collage'
      preLoaderRoute: typeof ImageCollageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/border': {
      id: '/image/border'
      path: '/image/border'
      fullPath: '/image/border'
      preLoaderRoute: typeof ImageBorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/blur': {
      id: '/image/blur'
      path: '/image/blur'
      fullPath: '/image/blur'
      preLoaderRoute: typeof ImageBlurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/adjust': {
      id: '/image/adjust'
      path: '/image/adjust'
      fullPath: '/image/adjust'
      preLoaderRoute: typeof ImageAdjustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/waveform': {
      id: '/audio/waveform'
      path: '/audio/waveform'
      fullPath: '/audio/waveform'
      preLoaderRoute: typeof AudioWaveformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/volume': {
      id: '/audio/volume'
      path: '/audio/volume'
      fullPath: '/audio/volume'
      preLoaderRoute: typeof AudioVolumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/trim': {
      id: '/audio/trim'
      path: '/audio/trim'
      fullPath: '/audio/trim'
      preLoaderRoute: typeof AudioTrimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/speed': {
      id: '/audio/speed'
      path: '/audio/speed'
      fullPath: '/audio/speed'
      preLoaderRoute: typeof AudioSpeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/reverse': {
      id: '/audio/reverse'
      path: '/audio/reverse'
      fullPath: '/audio/reverse'
      preLoaderRoute: typeof AudioReverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/remove-silence': {
      id: '/audio/remove-silence'
      path: '/audio/remove-silence'
      fullPath: '/audio/remove-silence'
      preLoaderRoute: typeof AudioRemoveSilenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/record': {
      id: '/audio/record'
      path: '/audio/record'
      fullPath: '/audio/record'
      preLoaderRoute: typeof AudioRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/normalize': {
      id: '/audio/normalize'
      path: '/audio/normalize'
      fullPath: '/audio/normalize'
      preLoaderRoute: typeof AudioNormalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/metadata': {
      id: '/audio/metadata'
      path: '/audio/metadata'
      fullPath: '/audio/metadata'
      preLoaderRoute: typeof AudioMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/merge': {
      id: '/audio/merge'
      path: '/audio/merge'
      fullPath: '/audio/merge'
      preLoaderRoute: typeof AudioMergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/fade': {
      id: '/audio/fade'
      path: '/audio/fade'
      fullPath: '/audio/fade'
      preLoaderRoute: typeof AudioFadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/denoise': {
      id: '/audio/denoise'
      path: '/audio/denoise'
      fullPath: '/audio/denoise'
      preLoaderRoute: typeof AudioDenoiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/convert': {
      id: '/audio/convert'
      path: '/audio/convert'
      fullPath: '/audio/convert'
      preLoaderRoute: typeof AudioConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/compress': {
      id: '/audio/compress'
      path: '/audio/compress'
      fullPath: '/audio/compress'
      preLoaderRoute: typeof AudioCompressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompressRoute: CompressRoute,
  DecryptRoute: DecryptRoute,
  DeleteRoute: DeleteRoute,
  DocxToPdfRoute: DocxToPdfRoute,
  DuplicateRoute: DuplicateRoute,
  EditRoute: EditRoute,
  EncryptRoute: EncryptRoute,
  ExtractImagesRoute: ExtractImagesRoute,
  GrayscaleRoute: GrayscaleRoute,
  HtmlToPdfRoute: HtmlToPdfRoute,
  ImagesToPdfRoute: ImagesToPdfRoute,
  MarkdownToPdfRoute: MarkdownToPdfRoute,
  MergeRoute: MergeRoute,
  MetadataRoute: MetadataRoute,
  OcrRoute: OcrRoute,
  OrganizeRoute: OrganizeRoute,
  PageNumbersRoute: PageNumbersRoute,
  PdfToEpubRoute: PdfToEpubRoute,
  PdfToImagesRoute: PdfToImagesRoute,
  PdfToPdfaRoute: PdfToPdfaRoute,
  PdfToTextRoute: PdfToTextRoute,
  PptxToPdfRoute: PptxToPdfRoute,
  PrivacyRoute: PrivacyRoute,
  ReverseRoute: ReverseRoute,
  RotateRoute: RotateRoute,
  SanitizeRoute: SanitizeRoute,
  SignRoute: SignRoute,
  SplitRoute: SplitRoute,
  TestCompressRoute: TestCompressRoute,
  WatermarkRoute: WatermarkRoute,
  XlsxToPdfRoute: XlsxToPdfRoute,
  AudioCompressRoute: AudioCompressRoute,
  AudioConvertRoute: AudioConvertRoute,
  AudioDenoiseRoute: AudioDenoiseRoute,
  AudioFadeRoute: AudioFadeRoute,
  AudioMergeRoute: AudioMergeRoute,
  AudioMetadataRoute: AudioMetadataRoute,
  AudioNormalizeRoute: AudioNormalizeRoute,
  AudioRecordRoute: AudioRecordRoute,
  AudioRemoveSilenceRoute: AudioRemoveSilenceRoute,
  AudioReverseRoute: AudioReverseRoute,
  AudioSpeedRoute: AudioSpeedRoute,
  AudioTrimRoute: AudioTrimRoute,
  AudioVolumeRoute: AudioVolumeRoute,
  AudioWaveformRoute: AudioWaveformRoute,
  ImageAdjustRoute: ImageAdjustRoute,
  ImageBlurRoute: ImageBlurRoute,
  ImageBorderRoute: ImageBorderRoute,
  ImageCollageRoute: ImageCollageRoute,
  ImageCompressRoute: ImageCompressRoute,
  ImageConvertRoute: ImageConvertRoute,
  ImageCropRoute: ImageCropRoute,
  ImageEditRoute: ImageEditRoute,
  ImageFaviconRoute: ImageFaviconRoute,
  ImageFiltersRoute: ImageFiltersRoute,
  ImageHeicToJpegRoute: ImageHeicToJpegRoute,
  ImagePaletteRoute: ImagePaletteRoute,
  ImageRemoveBgRoute: ImageRemoveBgRoute,
  ImageResizeRoute: ImageResizeRoute,
  ImageRotateRoute: ImageRotateRoute,
  ImageScreenshotRoute: ImageScreenshotRoute,
  ImageStripMetadataRoute: ImageStripMetadataRoute,
  ImageToBase64Route: ImageToBase64Route,
  ImageWatermarkRoute: ImageWatermarkRoute,
  QrBarcodeRoute: QrBarcodeRoute,
  QrBulkRoute: QrBulkRoute,
  QrGenerateRoute: QrGenerateRoute,
  QrScanRoute: QrScanRoute,
  VideoCompressRoute: VideoCompressRoute,
  VideoConvertRoute: VideoConvertRoute,
  VideoCropRoute: VideoCropRoute,
  VideoExtractAudioRoute: VideoExtractAudioRoute,
  VideoMetadataRoute: VideoMetadataRoute,
  VideoRemoveAudioRoute: VideoRemoveAudioRoute,
  VideoResizeRoute: VideoResizeRoute,
  VideoRotateRoute: VideoRotateRoute,
  VideoToGifRoute: VideoToGifRoute,
  VideoTrimRoute: VideoTrimRoute,
  AudioIndexRoute: AudioIndexRoute,
  ImageIndexRoute: ImageIndexRoute,
  QrIndexRoute: QrIndexRoute,
  VideoIndexRoute: VideoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
